### ISSUE TITLE
manifest filtering- requires double-encoding of & to properly get through

### ISSUE THREAD

**Issue by craigmc-ottera** [Eyevinn/channel-engine#45]
I've only been able to get this to work using a string like %28type%3D%3D"video"%2526%2526height<1000%29%2526%2526%28type%3D%3D"video"%2526%2526height>0%29

where you can see the double encoding of the ampersands %2526

Raw: 
(type=="video"&&height<1000)&&(type=="video"&&height>0)

Pre encoded
(type=="video"%26%26height<1000)%26%26(type=="video"%26%26height>0)

Fully encoded
%28type%3D%3D"video"%2526%2526height<1000%29%2526%2526%28type%3D%3D"video"%2526%2526height>0%29

otherwise the express/req middleware breaks up
req.query['filter'] = "(type="video""
req.query['height<1000'] = '';

identified and confirmed in engine/server.js line 234
 if (req.query['filter']) {
        debug(`Applying filter on master manifest ${req.query['filter']}`);
        filter = filterQueryParser(req.query['filter']);
      }

**Comment by birme** [comment]
Ah, alright. Thanks. Will build a unit test that reflects this together with a fix. Will put this on the backlog

**Comment by Nfrederiksen** [comment]
This is strange...
In the channel-engine we are using the restify framework and use the queryParser() plugin, which should be able to decode urlencoding porperly.
I tried running the example server.js provided in the repo, and also tested the restify queryParser() plugin on a seperate project, using the same version of restify.

I can't seem to reproduce this issue with the restify queryParser. 
Based on what you've shared, I assume the queryParser fails for you when inputing the following query string:

**filter=%28type%3D%3D"video"%26%26height<1000%29%26%26%28type%3D%3D"video"%26%26height>0%29**
 
 But this is still handled correctly by the queryParser on both server.js and on my isolated restify app.
 Could you share more details about the conditions for your failure case?

**Comment by craigmc-ottera** [comment]
Simply running it locally with a test channel
I try 
`[http;](http://localhost:8000/channels/jun_cg/master.m3u8?filter=%28type%3D%3D"video"%26%26height>200%29%26%26%28type%3D%3D"video"%26%26height<400%29)`

and get 
`  conditions.map((c) => {
             ^

TypeError: Cannot read properties of null (reading 'map')
    at filterQueryParser (/eyevinn-channel-engine/engine/util.js:7:14)
    at ChannelEngine._handleMasterManifest (/eyevinn-channel-engine/engine/server.js:463:18)
    at handleMasterRoute (/eyevinn-channel-engine/engine/server.js:112:20)
    at /eyevinn-channel-engine/engine/server.js:129:13
    at WebFrameworkShim.applySegment (/newrelic/lib/shim/shim.js:1430:20)
    at _applyRecorderSegment (/newrelic/lib/shim/shim.js:1021:20)
    at _doRecord (/newrelic/lib/shim/shim.js:1000:17)
    at /newrelic/lib/shim/shim.js:971:24
    at nextTick (/restify/lib/chain.js:167:13)
    at Shim.applySegment (/newrelic/lib/shim/shim.js:1430:20)
    at wrapper (/newrelic/lib/shim/shim.js:2092:17)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
`

Tossing in a breakpoint, I see that at that line, filterQuery value is  "(type==\"video\""

**Comment by Nfrederiksen** [comment]
Yes, thank you Craig. I see the issue now. I will see what we can do. Obviously, encoding the filter string beforehand is a hassle.
